<a href="https://colab.research.google.com/github/MarianiPedro/topicos_especiais_CNN/blob/main/numpy_exercises_student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Exercícios NumPy

In [2]:
import numpy as np

**1.** Crie um array com 6 elementos em que os elementos possuem o padrão a seguir:

```
[0 2 4 6 8 10]
```

In [ ]:
a = np.array(range(0,11,2))
print(a)

[ 0  2  4  6  8 10]


**2.** Crie um array $3 \times 4$ com o seguinte padrão:

```
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
 ```

In [ ]:
a = np.empty((3, 4))
for i in range(12):
    a[i//4, i%4] = i**2
print(a)

[[  0.   1.   4.   9.]
 [ 16.  25.  36.  49.]
 [ 64.  81. 100. 121.]]


**3.** Crie um array $7\times7$ no qual todos os elementos têm valor 0, exceto os da linha 3 e da coluna 3, que têm valor 1, como a seguir:

```
[[0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [1 1 1 1 1 1 1]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]]
```

In [ ]:
a = np.zeros((7, 7))
a[3] = 1
a[:,3] = 1
print(a)

[[0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]


**4.** Crie um array $5 \times 5$ com o seguinte padrão:

```
[[10  0  0  0  0]
 [ 0 10  0  0  0]
 [ 0  0 10  0  0]
 [ 0  0  0 10  0]
 [ 0  0  0  0 10]]
```

In [ ]:
a = np.empty((5, 5))
for x in range(a.shape[0]):
    for y in range(a.shape[1]):
      a[x,y] = 10 if x == y else 0
print(a)

[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]


**5.** Crie um array $5 \times 5$ com o seguinte padrão:

```
[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 25]]
```

Utilize as funções `np.diag` e `np.arange`.

In [ ]:
a = np.empty((5, 5))
for x in range(a.shape[0]):
    for y in range(a.shape[1]):
      a[x,y] = (x+1)*(y+1) if x == y else 0
print(a)

[[ 1.  0.  0.  0.  0.]
 [ 0.  4.  0.  0.  0.]
 [ 0.  0.  9.  0.  0.]
 [ 0.  0.  0. 16.  0.]
 [ 0.  0.  0.  0. 25.]]


**6.** Crie um array $3\times2\times4$ onde o elemento de índice $(i, j, k)$ tem valor $i^2$ para qualquer $j, k$, como abaixo:

```
[[[0 0 0 0]
  [0 0 0 0]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[4 4 4 4]
  [4 4 4 4]]]
```

Dica: utilize a função `np.indices`.

In [ ]:
# a = np.empty((3, 2, 4))
# for x in range(a.shape[0]):
#     a[x,:] = x**2
# print(a)

a = np.empty((3, 2, 4))
indices = np.indices(a.shape)
a = indices[0]**2

print(a)

[[[0 0 0 0]
  [0 0 0 0]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[4 4 4 4]
  [4 4 4 4]]]


**7.** Crie um array $5\times5$ onde o elemento de índice $(i,j)$ tem valor $i^2 + j^2$.

Dica: utilize a função `np.indices`.

In [ ]:
a = np.empty((5,5))
indices = np.indices(a.shape)
a = indices[0]**2+indices[1]**2

print(a)

[[ 0  1  4  9 16]
 [ 1  2  5 10 17]
 [ 4  5  8 13 20]
 [ 9 10 13 18 25]
 [16 17 20 25 32]]


**8.** Gere uma matriz $10\times10$ de números aleatórios com distribuição normal de média 0 e desvio padrão 1. Calcule o *máximo* valor em cada linha e o *mínimo* valor em cada coluna.

Dica: utilize a função `np.randn`.

In [ ]:
a = np.random.randn(10,10)
print(a)

[[-2.64430309  1.28243046  0.39518588  1.60715002 -0.41927435  0.06242385
  -0.89266229  2.33428499 -0.95218509 -0.79456674]
 [-0.4362049  -0.72035272 -1.49440342  0.87634198  1.71028361  0.79274186
   0.29811883 -0.85533486 -0.7086025  -0.59732226]
 [-1.28842193  0.75385728  0.88539004  0.33531034  1.33607677  0.76421395
   1.81651593 -0.06508958  0.44917035 -0.04978597]
 [ 1.67320315  0.84873584 -1.19526961  0.60241509 -0.09571205  0.0985125
   0.62020485 -1.06721446  1.26146298 -0.58322968]
 [ 0.71848918  0.23616391  0.40138897 -0.97823043  0.14609471  0.34789416
  -1.06446948 -1.40608928 -0.35915063  0.51039778]
 [-0.3849283   1.95972531  1.03056609 -1.52391559  1.29952196 -0.47331994
  -1.63629736 -1.11880814 -0.87684969  1.3714521 ]
 [-2.02851138 -0.87769783  1.63903979  1.56220378 -0.98791568 -0.73616128
  -0.62257331 -0.56982471  0.83493519 -0.44152384]
 [-2.9097023  -0.21435728  0.56843018  0.48435471 -0.82324634 -0.11483048
   0.09441953 -1.0769051  -0.94905222  1.51754214]
 

**9.** Gere uma matriz $X \in \mathbb{R}^{5\times5}$ de números aleatórios com distribuição normal de média 1 e desvio padrão 3, isto é, $X \sim \text{N}(1, 3)$. Depois gere uma matriz $Y$ de mesmo formato cujo elemento $(i,j)$ terá valor $1$ se o elemento $(i,j)$ da matriz aleatória for menor que -5 ou maior do que 7, e zero caso contrário.
Conte o número de valores diferentes de zero nessa nova matriz.

Dica: se $X \sim \text{N}(0, 1)$, então $(\sigma \cdot X + \mu) \sim \text{N}(\mu, \sigma)$.

In [7]:
x = np.random.normal(size=(5, 5), loc=1, scale=3)
y = np.empty((5,5))
for i in range(5):
  for j in range(5):
    y[i,j] = 1 if x[i,j] < -5 or x[i,j] > 7 else 0
print(x)
print(y)

[[-1.82313147  3.01554132  0.15207897  1.33524812 -1.92641313]
 [-3.42372238  5.29217895  3.7972665   7.5015844   1.54503478]
 [ 0.60680466  1.42562928  7.19915615 -2.48671391 -2.84396552]
 [-0.17129108 -3.02337177  3.59494463 -0.56505818  1.97906837]
 [ 3.60380677  0.24375167  3.38012161  5.92584295 -3.97010427]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


**10.** Use as regras de *broadcast* em seu benefício para gerar uma matriz $5\times5$ cujos elementos $(i,j)$ têm valor $i$. Faça o mesmo para gerar uma outra matriz de mesmo tamanho cujos elementos $(i,j)$ tenham valor $j$. Por fim, combine isso para gerar uma matriz também $5\times5$ cujos elementos $(i,j)$ tenham valor $2 i - j$.

Atenção: não utilizar `np.indices`.
Dica: utilizar soma com matriz de zeros com dimensões $10\times10$

In [30]:
zero = np.zeros((5,5))

x = np.arange(5).reshape(5, 1)
x = zero[:5, :5] + x
y = np.arange(5)
y = zero[:5, :5] + y
z = 2*x - y

print(x)
print(y)
print(z)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[ 0. -1. -2. -3. -4.]
 [ 2.  1.  0. -1. -2.]
 [ 4.  3.  2.  1.  0.]
 [ 6.  5.  4.  3.  2.]
 [ 8.  7.  6.  5.  4.]]


**11.** Considere a matriz

$
X = \begin{bmatrix}
  9 & 3 & 8 \\
  7 & 4 & 5 \\
  2 & 3 & 1 \\
  2 & 10 & 9 \\
  8 & 9 & 2 \\
\end{bmatrix}.
$

Calcule $X_{shifted} = X - \mu$, onde $\mu$ é a média das linhas de $X$. Explore a funcionalidade de broadcasting e não utilize loops.


In [29]:
X = np.array([[9, 3, 8], [7, 4, 5], [2, 3, 1], [2, 10, 9], [8, 9, 2]])
X_shifted = np.zeros(X.shape[1])  # change X_shifted bellow

med = np.mean(X, axis=0, keepdims=True)
X_shifted = X - med

ans = np.array([[3.4, -2.8, 3.0], [1.4, -1.8, 0.0], [-3.6, -2.8, -4.0], [-3.6, 4.2, 4.0], [2.4, 3.2, -3.0]])
are_equal = np.allclose(X_shifted, ans, atol=1e-5)
if are_equal:
    print("Your function is correct.")
else:
    print("Your function is not correct.")

Your function is correct.


**12.** A distância euclidiana entre dois vetores $u$ e $v$ de tamanho $n$ é dada por $\left\|u - v\right\|_2 = \sqrt{\sum_{i=1}^{n}(u_i - v_i)^2}.$

Dado os vetores (1-D arrays) a seguir, complete a função `euclidean_distance` para cálculo da distância. Não utilize loops, nem a função `np.linalg.norm`.

In [32]:
def euclidean_distance(u, v):
    distances = 0
    distances = np.sqrt(np.sum((u-v)**2))
    return distances


array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

distances = euclidean_distance(array1, array2)
are_equal = np.allclose(distances, np.linalg.norm(array1 - array2), atol=1e-5)
if are_equal:
    print("Your function is correct.")
else:
    print("Your function is not correct.")

Your function is correct.


**13.** Considere duas matrizes $X$ e $Y$, onde cada linha representa um vetor. Você foi solicitado a calcular a distância euclidiana entre as linhas de $X$ e as linhas correspondentes de $Y$. Escreva uma função que recebe as matrizes $X$ e $Y$ como entrada e retorna uma matriz $D$ onde cada elemento $(i,j)$ representa a distância euclidiana entre a linha $i$ de $X$ ($X_i$) e a linha $j$ de $Y$ ($Y_j$). O cálculo deve ser feito por meio de dois loops, conforme a equação

$D_{ij} = \left \|X_i - Y_j \right \|_2$

In [39]:
from scipy.spatial.distance import cdist


def calculate_distances_two_loops(X, Y):
    distances = np.zeros((X.shape[0], Y.shape[0]))
    for i in range(X.shape[0]):
        for j in range(Y.shape[0]):
            distances[i, j] = np.sqrt(np.sum((X[i]-Y[j])**2))
    return distances


X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
Y = np.array([[16, 17, 18], [19, 20, 21]])

distances = calculate_distances_two_loops(X, Y)
are_equal = np.allclose(distances, cdist(X, Y), atol=1e-5)
if are_equal:
    print("Your function is correct.")
else:
    print("Your function is not correct.")

[[25.98076211 31.17691454]
 [20.78460969 25.98076211]
 [15.58845727 20.78460969]
 [10.39230485 15.58845727]
 [ 5.19615242 10.39230485]]
Your function is correct.


**14.** O mesmo da questão anterior, mas agora utilizando um loop e broadcasting.

Dica: verifique se o resultado de `X[i] - Y` pode lhe ser útil na solução do exercício.

In [31]:
# Create two 1D numpy array
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
Y = np.array([[16, 17, 18], [19, 20, 21]])

i = 2
print(X[i] - Y)

[[ -9  -9  -9]
 [-12 -12 -12]]


In [41]:
def calculate_distances_one_loop(X, Y):
    distances = np.zeros((X.shape[0], Y.shape[0]))
    for i in range(X.shape[0]):
      distances[i] = np.sqrt(np.sum((X[i]-Y)**2, axis=1))
    print(distances)
    return distances


distances = calculate_distances_one_loop(X, Y)
are_equal = np.allclose(distances, cdist(X, Y), atol=1e-5)
if are_equal:
    print("Your function is correct.")
else:
    print("Your function is not correct.")

[[25.98076211 31.17691454]
 [20.78460969 25.98076211]
 [15.58845727 20.78460969]
 [10.39230485 15.58845727]
 [ 5.19615242 10.39230485]]
Your function is correct.


**15.** O mesmo da questão anterior, mas agora - você que é um mago do broadcasting - não pode utilizar loops.

Dica: verifique se o resultado de `X[:, np.newaxis, :] - Y` pode lhe ser útil na solução do exercício.

In [ ]:
# Create two 1D numpy array
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
Y = np.array([[16, 17, 18], [19, 20, 21]])

print(X[:, np.newaxis, :] - Y)

[[[-15 -15 -15]
  [-18 -18 -18]]

 [[-12 -12 -12]
  [-15 -15 -15]]

 [[ -9  -9  -9]
  [-12 -12 -12]]

 [[ -6  -6  -6]
  [ -9  -9  -9]]

 [[ -3  -3  -3]
  [ -6  -6  -6]]]


In [42]:
def calculate_distances_vectorized(X, Y):
    distances = np.zeros((X.shape[0], Y.shape[0]))
    distances[:, np.newaxis, :] = np.sqrt(np.sum((X-Y)**2))
    return distances


distances = calculate_distances_one_loop(X, Y)
are_equal = np.allclose(distances, cdist(X, Y), atol=1e-5)
if are_equal:
    print("Your function is correct.")
else:
    print("Your function is not correct.")

[[25.98076211 31.17691454]
 [20.78460969 25.98076211]
 [15.58845727 20.78460969]
 [10.39230485 15.58845727]
 [ 5.19615242 10.39230485]]
Your function is correct.
